name: mskapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.24.0
  firebase_auth: 3.4.2
  google_fonts: 2.1.1
  email_validator: 2.1.17
  cloud_firestore: 3.5.1
  get_cli: ^0.2.30
  image_picker: 0.8.6
  firebase_storage: 10.3.11
  flutter_email_sender: 5.1.0
  flutter_mailer: 2.0.1
  sendgrid_mailer: 0.1.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

